### PR TITLE
List

### PR DESCRIPTION
**Pull request by eakansh125**

### CODE REVIEW

**Review by AshutoshM29 — COMMENTED** [review]
Looks good to me, even the code is clean, you can merge it :)

**Review by Sahil25061999 — APPROVED** [review]
Super clean code , cant find any suggestions currently.😅

**Comment by eakansh125** [comment]
> Looks good to me, even the code is clean, you can merge it :)

Thanks :)

**Comment by eakansh125** [comment]
> Super clean code , cant find any suggestions currently.😅

Thanks :)

**Pull request merged**
